import type { BloomTheme, ThemeConfig } from "@/types";

export const THEMES: Record<BloomTheme, ThemeConfig> = {
  cozy: {
    id: "cozy",
    label: "Cozy",
    description: "Warm, comforting, like reading by a fireplace",
    emoji: "☕",
    gradient: {
      from: "#F7C5C0",
      to: "#FDF8F0",
      card: "rgba(253, 248, 240, 0.8)",
    },
    cssVars: {
      "--background": "35 60% 97%",
      "--foreground": "20 30% 20%",
      "--primary": "10 65% 65%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "35 40% 90%",
      "--secondary-foreground": "20 30% 25%",
      "--muted": "35 30% 93%",
      "--muted-foreground": "20 20% 50%",
      "--accent": "340 30% 85%",
      "--accent-foreground": "340 40% 30%",
      "--card": "35 50% 98%",
      "--card-foreground": "20 30% 20%",
      "--border": "35 30% 87%",
      "--ring": "10 65% 65%",
      "--radius": "1rem",
      "--gradient-start": "#F7C5C0",
      "--gradient-end": "#FDF8F0",
    },
    aiPersonaHint: "warm and comforting, like a trusted friend sharing scripture over a warm drink",
    targetAudience: "Anyone seeking warmth and comfort in their faith journey",
  },

  soft_feminine: {
    id: "soft_feminine",
    label: "Soft & Gentle",
    description: "Delicate, nurturing, with floral grace",
    emoji: "🌸",
    gradient: {
      from: "#F4C2D8",
      to: "#FAF0F7",
      card: "rgba(250, 240, 247, 0.85)",
    },
    cssVars: {
      "--background": "320 50% 97%",
      "--foreground": "320 30% 20%",
      "--primary": "330 55% 65%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "320 30% 91%",
      "--secondary-foreground": "320 30% 25%",
      "--muted": "320 25% 94%",
      "--muted-foreground": "320 20% 52%",
      "--accent": "300 25% 88%",
      "--accent-foreground": "300 40% 30%",
      "--card": "320 45% 98%",
      "--card-foreground": "320 30% 20%",
      "--border": "320 25% 88%",
      "--ring": "330 55% 65%",
      "--radius": "1.25rem",
      "--gradient-start": "#F4C2D8",
      "--gradient-end": "#FAF0F7",
    },
    aiPersonaHint: "gentle and nurturing, like a caring older sister who prays for you and sees your beauty",
    targetAudience: "Women and girls seeking gentle spiritual encouragement",
  },

  gamer: {
    id: "gamer",
    label: "Gamer Mode",
    description: "XP for your soul. Biblical truth with a controller in hand",
    emoji: "🎮",
    gradient: {
      from: "#4A1D8C",
      to: "#1A0A3C",
      card: "rgba(30, 15, 60, 0.9)",
    },
    cssVars: {
      "--background": "260 60% 8%",
      "--foreground": "260 20% 93%",
      "--primary": "270 80% 65%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "260 50% 18%",
      "--secondary-foreground": "260 20% 88%",
      "--muted": "260 40% 14%",
      "--muted-foreground": "260 20% 55%",
      "--accent": "200 80% 55%",
      "--accent-foreground": "200 80% 10%",
      "--card": "260 55% 12%",
      "--card-foreground": "260 20% 93%",
      "--border": "260 40% 22%",
      "--ring": "270 80% 65%",
      "--radius": "0.75rem",
      "--gradient-start": "#4A1D8C",
      "--gradient-end": "#1A0A3C",
    },
    aiPersonaHint: "energetic and direct, using game metaphors like levels, XP, and boss battles to explain spiritual growth",
    targetAudience: "Gamers, young men, and teens who relate to achievement systems",
  },

  minimalist: {
    id: "minimalist",
    label: "Minimalist",
    description: "Clean, focused, distraction-free faith",
    emoji: "◻️",
    gradient: {
      from: "#F5F5F3",
      to: "#FAFAFA",
      card: "rgba(255, 255, 255, 0.95)",
    },
    cssVars: {
      "--background": "0 0% 98%",
      "--foreground": "0 0% 12%",
      "--primary": "0 0% 15%",
      "--primary-foreground": "0 0% 98%",
      "--secondary": "0 0% 93%",
      "--secondary-foreground": "0 0% 20%",
      "--muted": "0 0% 95%",
      "--muted-foreground": "0 0% 50%",
      "--accent": "0 0% 90%",
      "--accent-foreground": "0 0% 15%",
      "--card": "0 0% 100%",
      "--card-foreground": "0 0% 12%",
      "--border": "0 0% 88%",
      "--ring": "0 0% 15%",
      "--radius": "0.5rem",
      "--gradient-start": "#F5F5F3",
      "--gradient-end": "#FAFAFA",
    },
    aiPersonaHint: "clear, precise, and thoughtful — like a wise mentor who says exactly what needs to be said with no excess",
    targetAudience: "Busy professionals and analytical thinkers who want depth without clutter",
  },

  healing_season: {
    id: "healing_season",
    label: "Healing Season",
    description: "Tender care for tender hearts",
    emoji: "🌿",
    gradient: {
      from: "#A8C5A0",
      to: "#E8F4E8",
      card: "rgba(232, 244, 232, 0.85)",
    },
    cssVars: {
      "--background": "120 35% 96%",
      "--foreground": "140 30% 15%",
      "--primary": "140 35% 45%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "120 25% 88%",
      "--secondary-foreground": "140 30% 20%",
      "--muted": "120 20% 92%",
      "--muted-foreground": "140 20% 48%",
      "--accent": "90 30% 85%",
      "--accent-foreground": "90 40% 25%",
      "--card": "120 30% 97%",
      "--card-foreground": "140 30% 15%",
      "--border": "120 25% 85%",
      "--ring": "140 35% 45%",
      "--radius": "1.25rem",
      "--gradient-start": "#A8C5A0",
      "--gradient-end": "#E8F4E8",
    },
    aiPersonaHint: "deeply compassionate and patient, meeting pain with grace, never rushing healing",
    targetAudience: "People going through grief, trauma, anxiety, or a difficult season",
  },

  student: {
    id: "student",
    label: "Student Life",
    description: "Scripture for the hustle and the late nights",
    emoji: "📚",
    gradient: {
      from: "#B8D4E8",
      to: "#EBF4FB",
      card: "rgba(235, 244, 251, 0.85)",
    },
    cssVars: {
      "--background": "210 55% 96%",
      "--foreground": "210 40% 15%",
      "--primary": "210 70% 50%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "210 40% 88%",
      "--secondary-foreground": "210 40% 20%",
      "--muted": "210 30% 92%",
      "--muted-foreground": "210 25% 50%",
      "--accent": "230 50% 80%",
      "--accent-foreground": "230 60% 25%",
      "--card": "210 50% 98%",
      "--card-foreground": "210 40% 15%",
      "--border": "210 35% 85%",
      "--ring": "210 70% 50%",
      "--radius": "0.875rem",
      "--gradient-start": "#B8D4E8",
      "--gradient-end": "#EBF4FB",
    },
    aiPersonaHint: "relatable and encouraging, like a campus minister who gets the pressure students face",
    targetAudience: "High school and college students navigating faith and academics",
  },

  busy_professional: {
    id: "busy_professional",
    label: "Busy Professional",
    description: "Concise, powerful daily faith for driven lives",
    emoji: "⚡",
    gradient: {
      from: "#2C3E6B",
      to: "#1A2545",
      card: "rgba(28, 38, 70, 0.9)",
    },
    cssVars: {
      "--background": "225 45% 10%",
      "--foreground": "225 20% 92%",
      "--primary": "210 75% 58%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "225 40% 18%",
      "--secondary-foreground": "225 20% 87%",
      "--muted": "225 35% 15%",
      "--muted-foreground": "225 20% 55%",
      "--accent": "170 60% 45%",
      "--accent-foreground": "170 60% 10%",
      "--card": "225 42% 14%",
      "--card-foreground": "225 20% 92%",
      "--border": "225 35% 22%",
      "--ring": "210 75% 58%",
      "--radius": "0.625rem",
      "--gradient-start": "#2C3E6B",
      "--gradient-end": "#1A2545",
    },
    aiPersonaHint: "efficient and direct with depth — no fluff, just truth that applies to a driven life",
    targetAudience: "Entrepreneurs, career-focused adults, and people with limited time",
  },

  kids_mode: {
    id: "kids_mode",
    label: "Kids Mode",
    description: "Bible adventures for little hearts",
    emoji: "🌈",
    gradient: {
      from: "#FFD580",
      to: "#FFF4CC",
      card: "rgba(255, 244, 204, 0.9)",
    },
    cssVars: {
      "--background": "45 100% 95%",
      "--foreground": "40 60% 20%",
      "--primary": "30 90% 58%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "200 80% 75%",
      "--secondary-foreground": "200 80% 15%",
      "--muted": "45 80% 90%",
      "--muted-foreground": "40 50% 45%",
      "--accent": "120 65% 65%",
      "--accent-foreground": "120 65% 15%",
      "--card": "45 90% 97%",
      "--card-foreground": "40 60% 20%",
      "--border": "45 60% 82%",
      "--ring": "30 90% 58%",
      "--radius": "1.5rem",
      "--gradient-start": "#FFD580",
      "--gradient-end": "#FFF4CC",
    },
    aiPersonaHint: "playful, safe, and simple — like a warm Sunday school teacher who makes Bible stories come alive",
    targetAudience: "Children ages 5-12 with parental guidance",
  },

  beginner_bible: {
    id: "beginner_bible",
    label: "Beginner Bible",
    description: "Every question is welcome here",
    emoji: "✨",
    gradient: {
      from: "#C4B5D0",
      to: "#F0EBF5",
      card: "rgba(240, 235, 245, 0.85)",
    },
    cssVars: {
      "--background": "280 35% 96%",
      "--foreground": "280 30% 18%",
      "--primary": "280 40% 52%",
      "--primary-foreground": "0 0% 100%",
      "--secondary": "280 25% 88%",
      "--secondary-foreground": "280 30% 22%",
      "--muted": "280 20% 92%",
      "--muted-foreground": "280 20% 52%",
      "--accent": "260 40% 82%",
      "--accent-foreground": "260 50% 25%",
      "--card": "280 30% 98%",
      "--card-foreground": "280 30% 18%",
      "--border": "280 25% 86%",
      "--ring": "280 40% 52%",
      "--radius": "1rem",
      "--gradient-start": "#C4B5D0",
      "--gradient-end": "#F0EBF5",
    },
    aiPersonaHint: "patient and clear, never assuming prior knowledge, welcoming every question with joy",
    targetAudience: "New believers, the spiritually curious, and those returning to faith",
  },
};

export const GARDEN_MILESTONES = [
  { stage: "seed", devotionalsRequired: 0, label: "Seed Planted", encouragement: "Your journey begins. Every great garden starts with a single seed.", emoji: "🌱" },
  { stage: "sprout", devotionalsRequired: 3, label: "First Sprout", encouragement: "Look at you growing! Three days of faithfulness is worth celebrating.", emoji: "🌿" },
  { stage: "bud", devotionalsRequired: 7, label: "Budding Faith", encouragement: "A full week with God. Your roots are going deeper.", emoji: "🌺" },
  { stage: "bloom", devotionalsRequired: 21, label: "In Full Bloom", encouragement: "21 days — a habit formed, a heart transformed. You are blooming beautifully.", emoji: "🌸" },
  { stage: "full_bloom", devotionalsRequired: 50, label: "Radiant Bloom", encouragement: "50 devotionals. This is not just consistency — this is transformation.", emoji: "🌻" },
  { stage: "garden", devotionalsRequired: 100, label: "A Full Garden", encouragement: "100 days of showing up. You've built a garden of faith that will last a lifetime.", emoji: "🌷" },
];
